AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for an Auto Scaling Group with Launch Template

Resources:
  # Define the Launch Template for the EC2 instances
  MyLaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateName: MyLaunchTemplate
      LaunchTemplateData:
        ImageId: ami-0c55b159cbfafe1f0  # Replace with your desired AMI ID
        InstanceType: t2.micro
        SecurityGroupIds:
          - !Ref MySecurityGroup
        KeyName: my-key-pair  # Replace with your key pair name
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: MyAutoScalingInstance

  # Define the Auto Scaling Group
  MyAutoScalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      VPCZoneIdentifier:
        - subnet-abc123456  # Replace with your subnet IDs
      LaunchTemplate:
        LaunchTemplateId: !Ref MyLaunchTemplate
        Version: !GetAtt MyLaunchTemplate.LatestVersionNumber
      MinSize: '1'
      MaxSize: '3'
      DesiredCapacity: '1'
      TargetGroupARNs:
        - arn:aws:elasticloadbalancing:region:account-id:targetgroup/my-target-group/abc123  # Replace with your target group ARN
      Tags:
        - Key: Name
          Value: MyAutoScalingGroupInstance
          PropagateAtLaunch: true

  # Define a Security Group for the EC2 instances
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security group for Auto Scaling instances
      VpcId: vpc-abc123456  # Replace with your VPC ID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0  # Allow SSH from anywhere (for demo purposes; secure this as needed)

Outputs:
  AutoScalingGroupName:
    Description: Name of the Auto Scaling Group
    Value: !Ref MyAutoScalingGroup

  LaunchTemplateID:
    Description: ID of the Launch Template
    Value: !Ref MyLaunchTemplate
