Parameters:
  AdminUsername:
    Type: String
    Description: "El nombre de usuario admin para el secreto"
    NoEcho: true # Oculta el valor en los logs de la consola
  AdminPassword:
    Type: String
    Description: "La contraseña del secreto"
    NoEcho: true # Oculta el valor en los logs de la consola
  CreationDate:
    Type: String
    Description: "Fecha de creación del secreto"
    NoEcho: true # Oculta el valor en los logs de la consola

Resources:
  MySecret:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Name: MySecretName # Cambia esto por el nombre deseado del secreto
      Description: "Este es un secreto creado por CloudFormation"
      SecretString: 
        Fn::Sub: |
          {
            "username": "${AdminUsername}",
            "password": "${AdminPassword}",
            "date": "${CreationDate}"
          }

Outputs:
  SecretArn:
    Value: !Ref MySecret
    Description: "El ARN del secreto creado"

# Explicación:
# - Los valores sensibles (AdminUsername, AdminPassword, CreationDate) se pasan como parámetros y se marcan con `NoEcho` para evitar que se registren o se muestren en la consola.
# - La función `Fn::Sub` combina los valores del secreto en un formato JSON que se almacena en Secrets Manager.
# - Este enfoque asegura que los valores sensibles no estén presentes en el template.
